name: Pull request automation

on:
  pull_request_target:
    types: [opened]
  push:
  workflow_run:
    workflows: ["Build Gutenberg Plugin Zip"]
    types:
      - completed

# The workflow started by the workflow_run event is able to access secrets and write tokens, even if the previous workflow was not. This is useful in cases where the previous workflow is intentionally not privileged, but you need to take a privileged action in a later workflow.
# does ^ present security problems? need to document any cautions?
# review https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions

# branches: [main]

jobs:
  pull-request-automation:
    runs-on: ubuntu-latest
    # maybe add this here -- if: ${{ github.event.workflow_run.conclusion == 'success' }} -- but would have to create seaprate job?
    # see if can just grab the conclusion from the payload or something
    steps:
    # Checkout defaults to using the branch which triggered the event, which
    # isn't necessarily `trunk` (e.g. in the case of a merge).
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      with:
        ref: trunk

    # Changing into the action's directory and running `npm install` is much
    # faster than a full project-wide `npm ci`.
    - run: cd packages/project-management-automation && npm install

    - uses: ./packages/project-management-automation
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
